@routeUrl=http://localhost:7071/api/v1

### Test Get Products Function
GET {{routeUrl}}/holiday-items
Content-Type: application/json

### Test Create Product
POST {{routeUrl}}/holiday-items
Content-Type: application/json

{
    "Name": "Another test",
    "Date": "2026-01-13T00:00:00",
    "Description": "Another test holiday"
}

### Test Delete Product
DELETE {{routeUrl}}/holiday-items/3
Content-Type: application/json